# Generated by Django 3.2 on 2022-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ThinkSoftRD', max_length=100, verbose_name='Company Name')),
                ('logo', models.ImageField(default='logo.jfif', upload_to='uploads', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(default='+92 315-0040764', max_length=100, verbose_name='Phone Number')),
                ('address', models.TextField(default='Khan House, Kot Ali Garh, Kasur', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Company info',
                'verbose_name_plural': 'Company Info',
            },
        ),
    ]
