# Generated by Django 3.2 on 2022-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='logo',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo_dark',
            field=models.ImageField(default='logo.jfif', upload_to='uploads', verbose_name='Logo Dark'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo_light',
            field=models.ImageField(default='logo.jfif', upload_to='uploads', verbose_name='Logo Light'),
        ),
    ]
