# Generated by Django 3.2 on 2022-01-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220126_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='favicon',
            field=models.ImageField(default='logo.jfif', upload_to='uploads', verbose_name='Favicon'),
        ),
    ]
